version: '3.3'
services:
    api_server:
        container_name: api_server
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/code/
        command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 5000
        ports:
            - 5000:5000
        depends_on: 
            - mysql_database


    mysql_database:
        container_name: mysql_database
        image: mysql:latest
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: prueba
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports: 
            - 3307:3307
volumes: 
    mysql_data:
